---
- name: Oosto v1 to v2 install
  hosts: all
  gather_facts: True
  tasks:

    - name: Clean up of old files
      include_role:
        name: cleanup
      when: ansible_kernel >= '4.18.0-305.25.1.el8_4.x86_64'
