---
- name: Oosto v1 to v2 install
  hosts: all
  gather_facts: True
  tasks:

    #  - name: Create a backup of oosto v1 data
    #  include_role:
    #    name: export_data

    - name: Convert workstation to server and update to latest RHEL 7
      include_role:
        name: wk2server
          #      when: oosto_backup.stat.exists 

    - name: Upgrade server from RHEL 7 to RHEL 8
      include_role:
        name: prep4rhel8
      when: kernel_version.stdout >= '3.10.0-1160.90.1.el7.x86_64'
