---
- name: install Minimal pkgs
  ansible.builtin.dnf:
    name: '@Minimal Install'
    state: present

- name: remove GUI pkgs
  ansible.builtin.dnf:
    name: '@Server with GUI'
    state: absent

- name: install basic server  pkgs
  ansible.builtin.dnf:
    name: '@Server'
    state: present

- name: Disable GUI on the system
  command: systemctl set-default -f multi-user.target

- name: Get all old RHEL 7 kernels
  find:
    paths: /lib/modules
    file_type: directory
    exclude: '*.el8*'
  register: old_kernel_files

- name: Remove weak modules for the old kernels
  command: /usr/sbin/weak-modules --remove-kernel {{ item.path | basename }}
  loop: "{{ old_kernel_files.files }}"

- name: Remove all old kernel entries from the boot loader
  command: /bin/kernel-install remove {{ item.path | basename }} /lib/modules/{{ item.path | basename }}/vmlinuz
  loop: "{{ old_kernel_files.files }}"

- name: Delete all the old kernels from the system
  file:
    state: absent
    path: "{{ item.path }}"
  loop: "{{ old_kernel_files.files }}"

- name: get old rescue kernels
  find:
    paths: /boot/
    patterns: "*rescue*"
    file_type: file
  register: rescue_files

- name: Remove the rescue kernels
  file:
    state: absent
    path: "{{ item.path }}"
  loop: "{{ rescue_files.files }}"
   
- name: Disable GUI in systemd
  command: systemctl set-default -f multi-user.target

- name: Gravity leave
  command: gravity leave --force
  ignore_errors: True

- name: Reboot the server
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: Run Oosto Clean for k8
  command: /home/1.24.2-8/clean.sh -k
  ignore_errors: True

- name: Run Oosto Clean for Docker
  command: /home/1.24.2-8/clean.sh -d
  ignore_errors: True

- name: Remove gravity folder
  file:
    path: /home/gravity
    state: absent

- name: remove symlink (ssd)
  file:
   path: /ssd
   state: absent

- name: umount the /home dir
  ansible.posix.mount:
    path: /home
    state: absent

- name: Remove the logocal volume for home
  community.general.lvol:
    vg: rhel
    lv: home
    state: absent
    force: True

- name: Extended the logical volume for /
  community.general.lvol:
    vg: rhel
    lv: root
    size: +100%FREE

- name: Grow the filesystem for /
  command: xfs_growfs /

- name: untar the onwatch file
  unarchive:
    src: /storage/onwatch_2.6.5-0_menards_rhel8.tar.gz
    dest: /opt
    remote_src: yes

- name: copy inventory file with updated hostname
  template:
    src: inventory.j2
    dest: /opt/ansible-installer-1.2.4-6/inventory/inventory_update.ini

- name: edit onwatch to enable HQ
  lineinfile:
     path: /opt/ansible-installer-1.2.4-6/inventory/product-versions/onwatch-2.6.5.yml
     regexp: '(hq_plugin:|\s+enable:)(.no)'
     line: '    enable: yes'
     backup: yes
