---

- name: Enable extra repos 
  ansible.builtin.yum:
    name: leapp-upgrade
    enablerepo: rhel-7-server-extras-rpms

- name: remove not needed modules
  modprobe:
    name: "{{item}}"
    state: absent
  with_items:
     - "pata_acpi"
     - "floppy"

- name: Remove kernel devel pkgs
  yum:
    name: kernel-devel-3.10.0-957.27.2.el7
    state: absent

- name: Remove adwaita-qt5-1.0-1.el7.x86_64
  yum:
    name:  adwaita-qt5-1.0-1.el7.x86_64
    state: absent

- name: Remove symlink
  file:
    path: /ssd
    state: absent
  ignore_errors: True

- name: copy leapp data
  copy:
    src: leapp-data.tar.gz
    dest: /tmp

- name: extract leapp data
  shell: tar -xzf /tmp/leapp-data.tar.gz -C /etc/leapp/files && rm /tmp/leapp-data.tar.gz

- name: Run pre leapp
  command: leapp preupgrade --target "{{ leaap_version }}"
  ignore_errors: True

- name: add leapp answers
  command: leapp answer --section remove_pam_pkcs11_module_check.confirm=True

- name: Run pre leapp
  command: leapp upgrade --target "{{ leaap_version }}"

- name: reboot the server
  command: reboot

# Tasks below not included as the upgrade to RHEL 8 takes a while and the task fails to report in a orderly time

#- name: check for kernel update
#  command: uname -r
#  register: kernel_version_two

#- name: Print Kernel
#  debug:
#    var: kernel_version_two

#- name: Kernel updated!
#  fail:
#    msg: Kernel is not updated {{ kernel_version.stdout }}
#  when: (kernel_version_two.stdout != '4.18.0-305.25.1.el8_4.x86_64')
