---

- name: Enable extra repos 
  ansible.builtin.yum:
    name: leapp-upgrade
    enablerepo: rhel-7-server-extras-rpms

- name: remove not needed modules
  modprobe:
    name: "{{item}}"
    state: absent
  with_items:
     - "pata_acpi"
     - "floppy"

- name: Remove kernel devel pkgs
  yum:
    name: kernel-devel-3.10.0-957.27.2.el7
    state: absent

- name: Remove adwaita-qt5-1.0-1.el7.x86_64
  yum:
    name:  adwaita-qt5-1.0-1.el7.x86_64
    state: absent

- name: Remove symlink
  file:
    path: /ssd
    state: absent
  ignore_errors: True

- name: copy leapp data
  copy:
    src: leapp-data.tar.gz
    dest: /tmp

- name: extract leapp data
  shell: tar -xzf /tmp/leapp-data.tar.gz -C /etc/leapp/files && rm /tmp/leapp-data.tar.gz

- name: Run pre leapp
  command: leapp preupgrade --target "{{ leaap_version }}"
  ignore_errors: True

- name: add leapp answers
  command: leapp answer --section remove_pam_pkcs11_module_check.confirm=True

- name: Run pre leapp
  command: leapp upgrade --target "{{ leaap_version }}"

- name: reboot the server
  command: reboot
