---
- name: Run installer
  command: './run-playbook.sh -i inventory/inventory_update.ini install-k3s.yml -t airgap'
  args:
    chdir: /opt/ansible-installer-1.2.4-6/


#- name: Run Oosto v2 dep install
#  command: /opt/ansible-installer-1.2.4-6/ansible-dep-installer.sh 

#- name: reboot
#  reboot:

#- name: extract migration tar file
#  unarchive:
#    src: /storage/v1_export.tar.gz
#    dest: /storage
#    remote_src: yes
