---
- name: File Transfer of Oosto
  hosts: all
  gather_facts: false
  tasks:

    - name: Get Sha of file
      stat:
        path: /tmp/somefile.txt
        checksum_algorithm: md5
        get_checksum: yes
      register: local_file
      delegate_to: localhost

    - name: Copy file over with bandwidth rate limit
      ansible.posix.synchronize:
        src: /tmp/somefile.txt
        dest: /tmp
        rsync_opts:
          - "--bwlimit=100000"
      delegate_to: localhost

    - name: get sha of remote file
      stat:
        path: /tmp/somefile.txt
        checksum_algorithm: md5
        get_checksum: yes
      register: remote_file

    - name: Verify integrity of file
      ansible.builtin.fail:
        msg: "File copy was not succesful"
      failed_when: remote_file.stat.checksum != local_file.stat.checksum

    - name: Test
      debug:
        msg: "next task"
